/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TPV.Interfaz;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import TPV.DB.ConsultasDb;
import TPV.Model.Producto;
import TPV.Gestion.Productos;
import TPV.Gestion.Usuarios;
import TPV.Model.Usuario;
import TPV.Model.Venta;
import TPV.Gestion.Ventas;



public class InterfazAdmin extends javax.swing.JFrame {

    
    DefaultListModel modeloListaUsuario;
    Usuarios listadoUsuarios;
    
    DefaultListModel modeloListaVenta;
    Ventas listadoVentas;
    
    DefaultListModel modeloListaProductos;
    Productos listadoProductos;
    
    ConsultasDb cbd;
    
    public InterfazAdmin() throws SQLException {
        this.modeloListaUsuario = new DefaultListModel();
        this.modeloListaVenta = new DefaultListModel();
        this.modeloListaProductos = new DefaultListModel();
        initComponents();
        
        this.cbd =new ConsultasDb();
        
        this.cargarUsuarios();
        this.cargarVentas();
        this.cargarProductos();
    }
    
    private void cargarUsuarios() throws SQLException{
        this.listadoUsuarios = new Usuarios(cbd.listarUsuariosPOO());
        this.modeloListaUsuario.clear();
        for (int i = 0; i < listadoUsuarios.getListadoUsuarios().size(); i++) {
            this.modeloListaUsuario.addElement(listadoUsuarios.getListadoUsuarios().get(i).getNombre());
        }
    }
    
    private void cargarVentas() throws SQLException{
        this.listadoVentas = new Ventas(cbd.listarVentas());
        this.modeloListaVenta.clear();
        for (int i = 0; i < this.listadoVentas.getListadoVentas().size(); i++) {
            this.modeloListaVenta.addElement(this.listadoVentas.getListadoVentas().get(i).getIdProducto());
        } 
    }
    
    private void cargarProductos() throws SQLException{
        this.listadoProductos = new Productos(cbd.listarProductos());
        this.modeloListaProductos.clear();
        for (int i = 0; i < this.listadoProductos.getListadoProductos().size(); i++) {
            this.modeloListaProductos.addElement(this.listadoProductos.getListadoProductos().get(i).getNombre());
            
        }
        
    }
    
    private void limpiarCamposUsuario(){
        this.txtNombreUsuario.setText("");
        this.txtApellidosUsuario.setText("");
        this.txtLoginUsuario.setText("");
        this.txtPasswordUsuario.setText("");
        
    }
    
    private void limpiarCamposVentas(){
        this.txtIdProductoVenta.setText("");
        this.txtCantidadVenta.setText("");
        this.txtNumeroTicketVenta.setText("");
        this.txtIdVentaVenta1.setText("");
    }
    
    private void limpiarCamposProductos(){
        this.txtIdProductoProducto.setText("");
        this.txtNombreProducto.setText("");
        this.txtPvpProducto.setText("");
        this.txtStockProductos.setText("");
        this.txtTipoProductos.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        panelProductos = new javax.swing.JPanel();
        lblNombreProducto = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        lblPvpProducto = new javax.swing.JLabel();
        txtPvpProducto = new javax.swing.JTextField();
        lblStockProducto = new javax.swing.JLabel();
        txtStockProductos = new javax.swing.JTextField();
        btnEliminarProductos = new javax.swing.JButton();
        btnNuevoProductos = new javax.swing.JButton();
        btnGuardarProductos = new javax.swing.JButton();
        lblIdProductoProducto = new javax.swing.JLabel();
        txtIdProductoProducto = new javax.swing.JTextField();
        lblTipoProducto = new javax.swing.JLabel();
        txtTipoProductos = new javax.swing.JTextField();
        txtImagenProductos = new javax.swing.JTextField();
        lblImagenProducto = new javax.swing.JLabel();
        btnAbrirImagenProductos1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        panelListaProductos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listProductos = new javax.swing.JList<>();
        lblVentas1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        panelVentas = new javax.swing.JPanel();
        lblIdProductoVenta = new javax.swing.JLabel();
        txtIdProductoVenta = new javax.swing.JTextField();
        lblNumeroTicketVenta = new javax.swing.JLabel();
        txtNumeroTicketVenta = new javax.swing.JTextField();
        lbCantidadVenta = new javax.swing.JLabel();
        txtCantidadVenta = new javax.swing.JTextField();
        btnEliminarVentas = new javax.swing.JButton();
        btnNuevoVentas = new javax.swing.JButton();
        btnGuardarVentas = new javax.swing.JButton();
        txtIdVentaVenta1 = new javax.swing.JTextField();
        lbIdVentaVenta1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelListaVentas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listVentas = new javax.swing.JList<>();
        lblVentas = new javax.swing.JLabel();
        Usuarios = new javax.swing.JPanel();
        panelListaUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUsuarios = new javax.swing.JList<>();
        lblUsuario = new javax.swing.JLabel();
        panelUsuarios = new javax.swing.JPanel();
        lblNombreUsuario = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        lblApellidoUsuario = new javax.swing.JLabel();
        txtApellidosUsuario = new javax.swing.JTextField();
        lblLoginUsuario = new javax.swing.JLabel();
        txtLoginUsuario = new javax.swing.JTextField();
        txtPasswordUsuario = new javax.swing.JTextField();
        lblPasswordUsuario = new javax.swing.JLabel();
        lblImagenUsuario = new javax.swing.JLabel();
        btnEliminarUsuario = new javax.swing.JButton();
        btnNuevoUsuario = new javax.swing.JButton();
        btnGuardarUsuario = new javax.swing.JButton();
        txtImangeUsuario = new javax.swing.JTextField();
        btnAbrirImagenUsuario1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 5));
        jTabbedPane1.setForeground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jTabbedPane1.setOpaque(true);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelProductos.setBackground(new java.awt.Color(255, 204, 51));

        lblNombreProducto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblNombreProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreProducto.setText("Nombre:");

        txtNombreProducto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        lblPvpProducto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblPvpProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblPvpProducto.setText("Pvp:");

        txtPvpProducto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        lblStockProducto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblStockProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblStockProducto.setText("Stock:");

        txtStockProductos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        btnEliminarProductos.setBackground(new java.awt.Color(255, 153, 0));
        btnEliminarProductos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnEliminarProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProductos.setText("Eliminar");
        btnEliminarProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 4));
        btnEliminarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductosActionPerformed(evt);
            }
        });

        btnNuevoProductos.setBackground(new java.awt.Color(255, 153, 0));
        btnNuevoProductos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnNuevoProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProductos.setText("Nuevo");
        btnNuevoProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 4));
        btnNuevoProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductosActionPerformed(evt);
            }
        });

        btnGuardarProductos.setBackground(new java.awt.Color(255, 153, 0));
        btnGuardarProductos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnGuardarProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarProductos.setText("Guardar");
        btnGuardarProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 4));
        btnGuardarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProductosActionPerformed(evt);
            }
        });

        lblIdProductoProducto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblIdProductoProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblIdProductoProducto.setText("Id producto:");

        txtIdProductoProducto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtIdProductoProducto.setEnabled(false);
        txtIdProductoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoProductoActionPerformed(evt);
            }
        });

        lblTipoProducto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblTipoProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoProducto.setText("Tipo:");

        txtTipoProductos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        txtImagenProductos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtImagenProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImagenProductosActionPerformed(evt);
            }
        });

        lblImagenProducto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblImagenProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblImagenProducto.setText("Imagen:");

        btnAbrirImagenProductos1.setBackground(new java.awt.Color(255, 153, 0));
        btnAbrirImagenProductos1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAbrirImagenProductos1.setForeground(new java.awt.Color(255, 255, 255));
        btnAbrirImagenProductos1.setText("Buscar archivo");
        btnAbrirImagenProductos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 4));
        btnAbrirImagenProductos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirImagenProductos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addComponent(lblIdProductoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdProductoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addComponent(lblStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtStockProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelProductosLayout.createSequentialGroup()
                                .addComponent(lblPvpProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPvpProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelProductosLayout.createSequentialGroup()
                                .addComponent(lblNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTipoProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtImagenProductos)
                                    .addComponent(btnAbrirImagenProductos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(26, 26, 26))
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addComponent(btnNuevoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblImagenProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTipoProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreProducto))
                .addGap(18, 18, 18)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPvpProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPvpProducto))
                .addGap(18, 18, 18)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockProductos))
                .addGap(18, 18, 18)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdProductoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdProductoProducto))
                .addGap(18, 18, 18)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoProductos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImagenProductos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrirImagenProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        jPanel4.add(panelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 370, 570));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        panelListaProductos.setBackground(new java.awt.Color(255, 204, 51));

        listProductos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        listProductos.setModel(modeloListaProductos);
        listProductos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listProductosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listProductos);

        lblVentas1.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblVentas1.setForeground(new java.awt.Color(255, 255, 255));
        lblVentas1.setText("PRODUCTOS");

        javax.swing.GroupLayout panelListaProductosLayout = new javax.swing.GroupLayout(panelListaProductos);
        panelListaProductos.setLayout(panelListaProductosLayout);
        panelListaProductosLayout.setHorizontalGroup(
            panelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(panelListaProductosLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblVentas1)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panelListaProductosLayout.setVerticalGroup(
            panelListaProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListaProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVentas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(panelListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Productos             ", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelVentas.setBackground(new java.awt.Color(0, 204, 0));

        lblIdProductoVenta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblIdProductoVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblIdProductoVenta.setText("IdProducto:");

        txtIdProductoVenta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        lblNumeroTicketVenta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblNumeroTicketVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroTicketVenta.setText("Numero de Ticket:");

        txtNumeroTicketVenta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        lbCantidadVenta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbCantidadVenta.setForeground(new java.awt.Color(255, 255, 255));
        lbCantidadVenta.setText("Cantidad:");

        txtCantidadVenta.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        btnEliminarVentas.setBackground(new java.awt.Color(255, 153, 0));
        btnEliminarVentas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnEliminarVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarVentas.setText("Eliminar");
        btnEliminarVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 4));
        btnEliminarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVentasActionPerformed(evt);
            }
        });

        btnNuevoVentas.setBackground(new java.awt.Color(255, 153, 0));
        btnNuevoVentas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnNuevoVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoVentas.setText("Nuevo");
        btnNuevoVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 4));
        btnNuevoVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoVentasActionPerformed(evt);
            }
        });

        btnGuardarVentas.setBackground(new java.awt.Color(255, 153, 0));
        btnGuardarVentas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnGuardarVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarVentas.setText("Guardar");
        btnGuardarVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 4));
        btnGuardarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarVentasActionPerformed(evt);
            }
        });

        txtIdVentaVenta1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtIdVentaVenta1.setEnabled(false);

        lbIdVentaVenta1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbIdVentaVenta1.setForeground(new java.awt.Color(255, 255, 255));
        lbIdVentaVenta1.setText("Id Venta:");

        javax.swing.GroupLayout panelVentasLayout = new javax.swing.GroupLayout(panelVentas);
        panelVentas.setLayout(panelVentasLayout);
        panelVentasLayout.setHorizontalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVentasLayout.createSequentialGroup()
                        .addComponent(btnNuevoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentasLayout.createSequentialGroup()
                        .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelVentasLayout.createSequentialGroup()
                                .addComponent(lbIdVentaVenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdVentaVenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelVentasLayout.createSequentialGroup()
                                .addComponent(lbCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelVentasLayout.createSequentialGroup()
                                .addComponent(lblNumeroTicketVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumeroTicketVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelVentasLayout.createSequentialGroup()
                                .addComponent(lblIdProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        panelVentasLayout.setVerticalGroup(
            panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdProductoVenta))
                .addGap(18, 18, 18)
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroTicketVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroTicketVenta))
                .addGap(18, 18, 18)
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCantidadVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadVenta))
                .addGap(18, 18, 18)
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdVentaVenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdVentaVenta1))
                .addGap(230, 230, 230)
                .addGroup(panelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        jPanel5.add(panelVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 370, 570));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        panelListaVentas.setBackground(new java.awt.Color(0, 204, 0));

        listVentas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        listVentas.setModel(modeloListaVenta);
        listVentas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listVentasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listVentas);

        lblVentas.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblVentas.setForeground(new java.awt.Color(255, 255, 255));
        lblVentas.setText("VENTAS");

        javax.swing.GroupLayout panelListaVentasLayout = new javax.swing.GroupLayout(panelListaVentas);
        panelListaVentas.setLayout(panelListaVentasLayout);
        panelListaVentasLayout.setHorizontalGroup(
            panelListaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelListaVentasLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblVentas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelListaVentasLayout.setVerticalGroup(
            panelListaVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListaVentasLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelListaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(panelListaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Ventas                   ", jPanel5);

        Usuarios.setBackground(new java.awt.Color(255, 255, 255));
        Usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelListaUsuarios.setBackground(new java.awt.Color(102, 153, 255));

        listUsuarios.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        listUsuarios.setModel(modeloListaUsuario);
        listUsuarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listUsuariosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listUsuarios);

        lblUsuario.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("USUARIOS");

        javax.swing.GroupLayout panelListaUsuariosLayout = new javax.swing.GroupLayout(panelListaUsuarios);
        panelListaUsuarios.setLayout(panelListaUsuariosLayout);
        panelListaUsuariosLayout.setHorizontalGroup(
            panelListaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListaUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsuario)
                .addGap(63, 63, 63))
        );
        panelListaUsuariosLayout.setVerticalGroup(
            panelListaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListaUsuariosLayout.createSequentialGroup()
                .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Usuarios.add(panelListaUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 510));

        panelUsuarios.setBackground(new java.awt.Color(102, 153, 255));

        lblNombreUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("Nombre:");

        txtNombreUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        lblApellidoUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblApellidoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidoUsuario.setText("Apeliidos:");

        txtApellidosUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        lblLoginUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblLoginUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginUsuario.setText("Login:");

        txtLoginUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtLoginUsuario.setEnabled(false);

        txtPasswordUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        lblPasswordUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblPasswordUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordUsuario.setText("Password:");

        lblImagenUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblImagenUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblImagenUsuario.setText("Imagen:");

        btnEliminarUsuario.setBackground(new java.awt.Color(255, 153, 0));
        btnEliminarUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnEliminarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarUsuario.setText("Eliminar");
        btnEliminarUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 4));
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });

        btnNuevoUsuario.setBackground(new java.awt.Color(255, 153, 0));
        btnNuevoUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnNuevoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoUsuario.setText("Nuevo");
        btnNuevoUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 4));
        btnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioActionPerformed(evt);
            }
        });

        btnGuardarUsuario.setBackground(new java.awt.Color(255, 153, 0));
        btnGuardarUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnGuardarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarUsuario.setText("Guardar");
        btnGuardarUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 4));
        btnGuardarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarUsuarioActionPerformed(evt);
            }
        });

        txtImangeUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N

        btnAbrirImagenUsuario1.setBackground(new java.awt.Color(255, 153, 0));
        btnAbrirImagenUsuario1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAbrirImagenUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        btnAbrirImagenUsuario1.setText("Eliminar");
        btnAbrirImagenUsuario1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255), 4));
        btnAbrirImagenUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirImagenUsuario1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUsuariosLayout = new javax.swing.GroupLayout(panelUsuarios);
        panelUsuarios.setLayout(panelUsuariosLayout);
        panelUsuariosLayout.setHorizontalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuariosLayout.createSequentialGroup()
                        .addComponent(btnNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUsuariosLayout.createSequentialGroup()
                                .addComponent(lblPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelUsuariosLayout.createSequentialGroup()
                                    .addComponent(lblLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelUsuariosLayout.createSequentialGroup()
                                        .addComponent(lblApellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtApellidosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelUsuariosLayout.createSequentialGroup()
                                        .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(panelUsuariosLayout.createSequentialGroup()
                            .addComponent(lblImagenUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAbrirImagenUsuario1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtImangeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelUsuariosLayout.setVerticalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(lblNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtApellidosUsuario)
                    .addComponent(lblApellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLoginUsuario)
                    .addComponent(lblLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPasswordUsuario)
                    .addComponent(lblPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagenUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImangeUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbrirImagenUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        Usuarios.add(panelUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 370, 570));

        jTabbedPane1.addTab("Usuarios              ", Usuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //BOTONES NUEVO
    
    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed
        // TODO add your handling code here:
        this.limpiarCamposUsuario();
    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

    private void btnNuevoVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoVentasActionPerformed
        // TODO add your handling code here:
        this.limpiarCamposVentas();
    }//GEN-LAST:event_btnNuevoVentasActionPerformed

    private void btnNuevoProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductosActionPerformed
        // TODO add your handling code here:
        this.limpiarCamposProductos();
    }//GEN-LAST:event_btnNuevoProductosActionPerformed

    //BOTONES GUARDAR
    private void btnGuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUsuarioActionPerformed
        // TODO add your handling code here:
        try {
            if(txtLoginUsuario.getText().equals("")){
                    //this.cbd.insertarUsuario(new Usuario(this.txtNombreUsuario.getText(),this.txtApellidosUsuario.getText(),0 ,Integer.parseInt(this.txtPasswordUsuario.getText()), null));
                    this.cargarUsuarios();
            }else{
               // this.cbd.modificarUsuario(new Usuario(this.txtNombreUsuario.getText(),this.txtApellidosUsuario.getText(),Integer.parseInt(this.txtLoginUsuario.getText()),Integer.parseInt(this.txtPasswordUsuario.getText()), null));
                this.cargarUsuarios();
            }
        } catch (SQLException ex) {
                Logger.getLogger(InterfazAdmin.class.getName()).log(Level.SEVERE, null, ex);
                
            }
    }//GEN-LAST:event_btnGuardarUsuarioActionPerformed

    private void btnGuardarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarVentasActionPerformed
        // TODO add your handling code here:
        try {
            if(txtIdVentaVenta1.getText().equals("")){
                    this.cbd.insertarVenta(new Venta(Integer.parseInt(this.txtIdProductoVenta.getText()),Integer.parseInt(this.txtNumeroTicketVenta.getText()),Integer.parseInt(this.txtCantidadVenta.getText()),0));
                    this.cargarVentas(); 
            }else{
                    this.cbd.modificarVenta(new Venta(Integer.parseInt(this.txtIdProductoVenta.getText()),Integer.parseInt(this.txtNumeroTicketVenta.getText()),Integer.parseInt(this.txtCantidadVenta.getText()),0));
                    this.cargarVentas(); 
            }
        } catch (SQLException ex) {
                Logger.getLogger(InterfazAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnGuardarVentasActionPerformed

    private void btnGuardarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductosActionPerformed
        // TODO add your handling code here:
        try {
            if(txtIdProductoProducto.getText().equals("")){
                    this.cbd.insertarProducto(new Producto(this.txtNombreProducto.getText(),Float.parseFloat(this.txtPvpProducto.getText()),Integer.parseInt(this.txtStockProductos.getText()),0, this.txtTipoProductos.getText()));
                    this.cargarProductos(); 
            }else{
                    this.cbd.modificarProducto(new Producto(this.txtNombreProducto.getText(),Float.parseFloat(this.txtPvpProducto.getText()),Integer.parseInt(this.txtStockProductos.getText()),Integer.parseInt(this.txtIdProductoProducto.getText()), this.txtTipoProductos.getText()));
                    this.cargarProductos();
            }
        } catch (SQLException ex) {
                Logger.getLogger(InterfazAdmin.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_btnGuardarProductosActionPerformed

    //bOTONES ELIMINAR
    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        // TODO add your handling code here:
        if(listUsuarios.getSelectedIndex()>=0){
            try {
                this.cbd.eliminarUsuario(this.listadoUsuarios.get(listUsuarios.getSelectedIndex()));
                cargarUsuarios();
            } catch (SQLException ex) {
                Logger.getLogger(InterfazAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnEliminarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVentasActionPerformed
        // TODO add your handling code here:
        if(listVentas.getSelectedIndex()>=0){
            try {
                this.cbd.eliminarVenta(this.listadoVentas.get(this.listVentas.getSelectedIndex()));
                cargarVentas();
            } catch (SQLException ex) {
                Logger.getLogger(InterfazAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnEliminarVentasActionPerformed

    private void btnEliminarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductosActionPerformed
        // TODO add your handling code here:
        if(listProductos.getSelectedIndex()>=0){
            try {
                this.cbd.eliminarProducto(this.listadoProductos.get(this.listProductos.getSelectedIndex()));
                cargarProductos();
            } catch (SQLException ex) {
                Logger.getLogger(InterfazAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnEliminarProductosActionPerformed

    //CAMBIOS DE VALORES EN LAS LISTAS
    private void listUsuariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listUsuariosValueChanged
        // TODO add your handling code here:
        if(listUsuarios.getSelectedIndex()>=0){
            Usuario user = new Usuario();
            user = listadoUsuarios.get(listUsuarios.getSelectedIndex());
            this.txtNombreUsuario.setText(user.getNombre());
            this.txtApellidosUsuario.setText(user.getApellidos());
            this.txtLoginUsuario.setText(String.valueOf(user.getLogin()));
            this.txtPasswordUsuario.setText(String.valueOf(user.getPassword()));
        }
    }//GEN-LAST:event_listUsuariosValueChanged

    private void listVentasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listVentasValueChanged
        // TODO add your handling code here:
        if(listVentas.getSelectedIndex()>=0){
            Venta venta = new Venta();
            venta = this.listadoVentas.get(listVentas.getSelectedIndex());
            this.txtIdProductoVenta.setText(String.valueOf(venta.getIdProducto()));
            this.txtNumeroTicketVenta.setText(String.valueOf(venta.getNumeroTicket()));
            this.txtCantidadVenta.setText(String.valueOf(venta.getCantidad()));
            this.txtIdVentaVenta1.setText(String.valueOf(venta.getIdVenta()));
        }
    }//GEN-LAST:event_listVentasValueChanged

    private void listProductosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listProductosValueChanged
        // TODO add your handling code here:
        if(listProductos.getSelectedIndex()>=0){
            Producto prod = new Producto();
            prod = this.listadoProductos.get(listProductos.getSelectedIndex());
            this.txtNombreProducto.setText(prod.getNombre());
            this.txtPvpProducto.setText(String.valueOf(prod.getPvp()));
            this.txtStockProductos.setText(String.valueOf(prod.getStock()));
            this.txtIdProductoProducto.setText(String.valueOf(prod.getIdProducto()));
            this.txtTipoProductos.setText(prod.getTipo());
        }
    }//GEN-LAST:event_listProductosValueChanged

    private void txtIdProductoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoProductoActionPerformed

    private void txtImagenProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImagenProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImagenProductosActionPerformed

    private void btnAbrirImagenProductos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirImagenProductos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbrirImagenProductos1ActionPerformed

    private void btnAbrirImagenUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirImagenUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbrirImagenUsuario1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazAdmin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(InterfazAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Usuarios;
    private javax.swing.JButton btnAbrirImagenProductos1;
    private javax.swing.JButton btnAbrirImagenUsuario1;
    private javax.swing.JButton btnEliminarProductos;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnEliminarVentas;
    private javax.swing.JButton btnGuardarProductos;
    private javax.swing.JButton btnGuardarUsuario;
    private javax.swing.JButton btnGuardarVentas;
    private javax.swing.JButton btnNuevoProductos;
    private javax.swing.JButton btnNuevoUsuario;
    private javax.swing.JButton btnNuevoVentas;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCantidadVenta;
    private javax.swing.JLabel lbIdVentaVenta1;
    private javax.swing.JLabel lblApellidoUsuario;
    private javax.swing.JLabel lblIdProductoProducto;
    private javax.swing.JLabel lblIdProductoVenta;
    private javax.swing.JLabel lblImagenProducto;
    private javax.swing.JLabel lblImagenUsuario;
    private javax.swing.JLabel lblLoginUsuario;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblNumeroTicketVenta;
    private javax.swing.JLabel lblPasswordUsuario;
    private javax.swing.JLabel lblPvpProducto;
    private javax.swing.JLabel lblStockProducto;
    private javax.swing.JLabel lblTipoProducto;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JLabel lblVentas1;
    private javax.swing.JList<String> listProductos;
    private javax.swing.JList<String> listUsuarios;
    private javax.swing.JList<String> listVentas;
    private javax.swing.JPanel panelListaProductos;
    private javax.swing.JPanel panelListaUsuarios;
    private javax.swing.JPanel panelListaVentas;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel panelUsuarios;
    private javax.swing.JPanel panelVentas;
    private javax.swing.JTextField txtApellidosUsuario;
    private javax.swing.JTextField txtCantidadVenta;
    private javax.swing.JTextField txtIdProductoProducto;
    private javax.swing.JTextField txtIdProductoVenta;
    private javax.swing.JTextField txtIdVentaVenta1;
    private javax.swing.JTextField txtImagenProductos;
    private javax.swing.JTextField txtImangeUsuario;
    private javax.swing.JTextField txtLoginUsuario;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtNumeroTicketVenta;
    private javax.swing.JTextField txtPasswordUsuario;
    private javax.swing.JTextField txtPvpProducto;
    private javax.swing.JTextField txtStockProductos;
    private javax.swing.JTextField txtTipoProductos;
    // End of variables declaration//GEN-END:variables
}
